### ISSUE TITLE
Missing information compare to HTML report

### ISSUE THREAD

**Issue by mathieusimon** [stevespringett/dependency-check-sonar-plugin#31]
Hello there,

It looks like the vulnerability issues coming from the dependency-check xml report lacks of information compare to the HTML output.
Basically everything is reflected on SonarQube issue except we can call "Confirmation links" that corroborate the vulnerability raised by the tool.

Why this discrepancy?
Regards,

**Comment by stevespringett** [comment]
In SQ 5.x it was not possible to set text formatting in Markdown or HTML format. So if a description included a list of URLs, there was no way to format that list. The UX of that design choice prevents this type of functionality.

I have not investigated to see if SQ 6.x includes basic formatting options or not. If so, I will be adding this, but if not, it will remain the way it is.

**Comment by mathieusimon** [comment]
Thanks for this quick answer. Very appreciated.

**Comment by NickHarvey2** [comment]
Hi, I was considering putting together a pull request for adding formatting to to SonarQube messages once https://jira.sonarsource.com/browse/SONAR-4161 is complete and available in SQ 7.x - this functionality would be really useful for my team.

Is there a certain format you were thinking? I have at least one specific idea that I'd like to implement, but other than that I would be open to whatever.

**Comment by stevespringett** [comment]
@NickHarvey2 Thanks for checking, but no, I didn't have any specific ideas in mind. The goal is to really just format it in a way that provides increased usability so, at a glance, a user can quickly determine what the issue is and in what component. If you have an idea that will accomplish that, then by all mean, a pull request would certainly be welcome.

The enhancement request is quite old. I've been waiting several years for SonarSource to implement it. If more people flood their mailing list with this request, they might prioritize it a bit higher.

**Comment by stevespringett** [comment]
Closing as @NickHarvey2 has put together a method by which the actual DC HTML report is embedded inside the SQ project.
