### ISSUE TITLE
Do you have a Sonarqube 6.x compatible release/binary?

### ISSUE THREAD

**Issue by clj2289** [stevespringett/dependency-check-sonar-plugin#37]

**Comment by stevespringett** [comment]
I plan on having a binary when a 6.x LTS release is made available. Not a lot of testing is done on non-LTS releases since SonarSource usually makes a lot of critical changes between these point releases often breaking things in the process. This is why for non-LTS usage, you'll need to compile yourself. Not sure if 6.4 or 6.5 will be LTS, but I do know it's getting close.

**Comment by durandx** [comment]
We use the version builded from master (1.1.0-SNAPSHOT commit 33c5bf8b6181fed201ce302de624ad5903b95874).
It is working fine so far with Sonar Qube Version 6.3 (build 19869)...

**Comment by stephanerenou** [comment]
Looks like next LTS is scheduled for October with a release 6.7:
https://groups.google.com/forum/#!searchin/sonarqube/LTS%7Csort:date/sonarqube/mYNxFeovqgM/wRiVI72UAgAJ

**Comment by bradflood** [comment]
SonarQube 6 LTS is 6.7, set for release on Oct 6. (https://jira.sonarsource.com/browse/SONAR/fixforversion/13972/)

Steve: I am converting another sonarqube plugin from v5 LTS to v6 LTS so have the changes fresh in my mind.  I am willing to submit a PR in a few weeks for dependency-check-sonar-plugin that is modified to comply with SQ 6 LTS APIs. Let me know if you'd like me to do that.

**Comment by stevespringett** [comment]
Within the next day or two I'll be pushing out a binary for 6.3+

Closing
