### ISSUE TITLE
RFC: support minimum score for blocker issues

### ISSUE THREAD

**Issue by walterdeboer** [stevespringett/dependency-check-sonar-plugin#62]
We can now specify MINOR (cvss: low), MAJOR cvss: medium) and CRITICAL (cvss: high) errors, but CVSS v3.0 Ratings also specifies "critical" (https://nvd.nist.gov/vuln-metrics/cvss). This can be mapped to the SonarQube severity category BLOCKER.

**Comment by stevespringett** [comment]
Dependency-Check currently uses the XML data feeds. The XML feeds only support CVSSv2. So the calculation of the score and the score itself, need to conform to the CVSSv2 spec of what makes an issue low, medium, or high severity.

You're correct in that CVSSv3 introduces critical, but Dependency-Check will need to move from using the XML feed to the JSON feed in order to be able to support CVSSv3. Refer to https://github.com/jeremylong/DependencyCheck/issues/707 on when support for the JSON feed is coming.

**Comment by stevespringett** [comment]
Ideally, the SonarQube plugin will be able to distinguish between vulnerabilities calculated with CVSSv2 and CVSSv3 within the same report and rate each vulnerability according to each specification. It should also be able to distinguish if an entire report was uploaded that only supported CVSSv2 and present the severity according to just the v2 spec.

**Comment by walterdeboer** [comment]
Ah, I see it is more complicated. I wasn't aware of that. Regardless it would be nice maybe to be able to mark isues as blocker in stead of critical? But the default shoudl be -1 then for now..

**Comment by Reamer** [comment]
You are now quite flexibly to map the CVSS Score based on you needs.
Check the defaults out at https://github.com/stevespringett/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckConstants.java#L31-L34
