### ISSUE TITLE
Vulnerability Duplicates

### ISSUE THREAD

**Issue by devpsi** [stevespringett/dependency-check-sonar-plugin#65]
Hello. Is it possible to get rid of all the vulnerability duplicates from showing up in SonarQube? We have the same vulnerability showing up hundreds of times. Thank you in advance, please let me know if you have any questions or need more details.

SonarQube: Version 7.0 (build 36138)
OWASP Dependency Check: Version 3.2.1

Vulnerability:
Filename: NLog.dll | Reference: CVE-1999-1278 | CVSS Score: 7.5 | nlog CGI scripts do not properly filter shell metacharacters from the IP address argument, which could allow remote attackers to execute certain commands via (1) nlog-smb.pl or (2) rpc-nlog.pl.

**Comment by stevespringett** [comment]
If the Dependency-Check report has the same issue hundreds of times, then there are actually hundreds of unique instances of that vulnerability in the project being scanned.

If you're referring to the same vulnerability showing up between multiple SonarQube projects/modules, there's nothing a plugin can do to normalize and deduplicate that. Plugins like Dependency-Check only do two things, read in a report and tell SonarQube what the issues are. From there, it's up to SQ to sort it out.

If the vulnerability you're concerned about is a false positive, you can suppress the false positive during the execution of the Dependency-Check analysis. When reading in the reports, the SQ plugin will see the issue has been suppressed and will not import it. If the issue is not a false positive, then you may want to look into a vulnerability aggregation and normalization platform such as Kenna Security or ThreadFix. Also, Dependency-Track does a bit of this, just not across projects, but it will normalize within the same project.

Refer to https://jeremylong.github.io/DependencyCheck/general/suppression.html for info on how suppressions work.

**Comment by devpsi** [comment]
Perfect! Thank you for taking the time to reply; we appreciate it.
